apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot-meter

resources:
  - ../../base
  - persistent-volumes.yaml

patches:
  - path: patches/mosquitto-exposure.yaml
  - path: patches/device-manager-nodeport.yaml
  - path: patches/simulator-replicas.yaml
  - path: patches/pvc-storage-class.yaml
