apiVersion: v1
kind: Secret
metadata:
  name: iot-meter-secrets
  namespace: iot-meter
  labels:
    app.kubernetes.io/part-of: iot-meter
type: Opaque
stringData:
  # PostgreSQL
  DB_USER: "iot_user"
  DB_PASSWORD: "iot_password"
  POSTGRES_DB: "iot_devices"
  POSTGRES_USER: "iot_user"
  POSTGRES_PASSWORD: "iot_password"

  # InfluxDB
  INFLUXDB_TOKEN: "iot-admin-token-secret-12345"
  DOCKER_INFLUXDB_INIT_USERNAME: "admin"
  DOCKER_INFLUXDB_INIT_PASSWORD: "adminpassword"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "iot-admin-token-secret-12345"

  # MinIO
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin123"
